# Added for Automated IDS Update
%tr = (
%tr,
'idsupdate update status' => 'Rule update status',
'idsupdate update failed' => 'Rule update failed',
'idsupdate update partial' => 'Rule update partially completed',
'idsupdate update success' => 'Rule update successful',
'idsupdate ids update log' => 'IDS Update Logs',
'idsupdate ids update log viewer' => 'IDS Update log viewer',
'idsupdate updates' => 'Number of rule updates for',
'idsupdate active rules' => 'Number of active rules',
'idsupdate ruleset' => 'Ruleset',
'idsupdate new rules' => 'New rules',
'idsupdate enabled' => 'Enabled',
'idsupdate disabled' => 'Disabled',
'idsupdate deleted rules' => 'Deleted rules',
'idsupdate updated rules' => 'Updated rules',
'idsupdate changed enabled' => 'Enabled rules that have changed',
'idsupdate consider disabling' => 'The following enabled rules have changed that would normally be disabled in the currently selected policy. ' .
                                  'It is worth considering whether the reasons they were enabled are still valid.',
'idsupdate changed disabled' => 'Disabled rules that have changed',
'idsupdate consider enabling' => 'The following disabled rules have changed that would normally be enabled in the currently selected policy. ' .
                                 'It is worth considering whether the reasons they were disabled are still valid.',
'idsupdate enabled' => 'Rules that have been enabled',
'idsupdate enabled due to policy change' => 'The following rules have been enabled due to a change in policy',
'idsupdate disabled' => 'Rules that have been disabled',
'idsupdate disabled due to policy changed' => 'The following rules have been disabled due to a change in policy',
'idsupdate change' => 'Change',
'idsupdate from' => 'From',
'idsupdate to' => 'To',
'idsupdate none found' => 'None found in active rule files',
'idsupdate unrecognised log messages' => 'Unknown Entries',
'idsupdate flowbit warnings' => 'There are warnings for flowbits being tested in the active rules without being set.',
'idsupdate flowbit warning list' => 'Intrusion Detection System rule flowbit warnings',
'idsupdate flowbit warning explaination' => 'Flowbits allow one IDS rule to affect subsequent rules.  The following list is of rules which ' .
                                            'test the value of flowbits but where no active rule sets the flowbit.  Either the rule testing ' .
                                            'the flowbit should be disabled or the rule setting the flowbit should be enabled.',
'idsupdate flowbit file not found' => 'There are no flowbit warnings at this time.',
'idsupdate name' => 'Name',
'idsupdate state' => 'State',
'idsupdate type' => 'Type',
'idsupdate group' => 'Group',
'idsupdate test' => 'Test',
'idsupdate set' => 'Set/Unset',
'idsupdate flowbit update time' => 'Flowbit warnings updated at',
'idsupdate ids update' => 'IDS Update',
'idsupdate config' => 'Configuration',
'idsupdate enable automatic update' => 'Enable automatic updates',
'idsupdate rate' => 'Update rate',
'idsupdate download limit' => 'Download limit (kbit/s)',
'idsupdate default policy' => 'Default policy',
'idsupdate live update' => 'Enable live update',
'idsupdate enable email' => 'Send emails',
'idsupdate apply policy change' => 'Apply policy changes',
'idsupdate policy connectivity' => 'Connectivity',
'idsupdate policy balanced' => 'Balanced',
'idsupdate policy security' => 'Security',
'idsupdate policy max-detect' => 'Max-Detect',
'idsupdate hourly' => 'Hourly',
'idsupdate daily' => 'Daily',
'idsupdate weekly' => 'Weekly',
'idsupdate status' => 'Status',
'idsupdate ruleset' => 'Ruleset',
'idsupdate last updated' => 'Last updated',
'idsupdate invalid input for download limit' => 'Invalid input for download limit'
);
