# Added for Automated IDS Update accounting
%tr = (
%tr,
'idsupdate update status' => 'Statut de mise à jour',
'idsupdate update failed' => 'Échec de la mise à jour',
'idsupdate update partial' => 'Mise à jour de la règle partiellement terminée',
'idsupdate update success' => 'Mise à jour des règles réussie',
'idsupdate ids update log' => 'Journaux de mise à jour IDS',
'idsupdate ids update log viewer' => 'IDS Update viewer du journal',
'idsupdate updates' => 'Nombre de mises à jour de règle pour',
'idsupdate active rules' => 'Nombre de règles actives',
'idsupdate ruleset' => 'Ensemble de règles',
'idsupdate new rules' => 'Nouvelles règles',
'idsupdate enabled' => 'Activée',
'idsupdate disabled' => 'Désactivé',
'idsupdate deleted rules' => 'Règles supprimées',
'idsupdate updated rules' => 'Règles mises à jour',
'idsupdate changed enabled' => 'Règles activées qui ont changé',
'idsupdate consider disabling' => 'Les règles activées suivantes ont été modifiées et normalement désactivées dans la stratégie actuellement ' .
                                'sélectionnée. Il est utile de vérifier si les raisons pour lesquelles elles ont été activées sont toujours ' .
                                'valables.',
'idsupdate changed disabled' => 'Règles désactivées qui ont changé',
'idsupdate consider enabling' => 'Les règles désactivées suivantes ont été modifiées, normalement activées dans la stratégie actuellement ' .
                               'sélectionnée. Il est utile de vérifier si les raisons pour lesquelles elles ont été désactivées sont toujours ' .
                               'valables.',
'idsupdate enabled' => 'Nouvelles règles activées',
'idsupdate enabled due to policy change' => "Les règles suivantes ont été activées en raison d'un changement de politique",
'idsupdate disabled' => 'Nouvelles règles qui ont été désactivées',
'idsupdate disabled due to policy changed' => "Les règles suivantes ont été désactivées en raison d'un changement de politique",
'idsupdate change' => 'Changement',
'idsupdate from' => 'De',
'idsupdate to' => 'À',
'idsupdate none found' => 'Aucune trouvée dans les fichiers de règles actives',
'idsupdate unrecognised log messages' => 'Entrées inconnues',
'idsupdate flowbit warnings' => 'Il y a des avertissements pour les flowbits testés dans les règles actives sans être défini.',
'idsupdate flowbit warning list' => "Alerte de débit de règle du système de détection d'intrusion",
'idsupdate flowbit warning explaination' => "Les Flowbits permettent à une règle IDS d'affecter les règles suivantes. La liste suivante " .
                                          "répertorie les règles qui testent la valeur de flowbits mais où aucune règle active ne définit " .
                                          "la Flowbit. La règle testant le flux doit être désactivée ou le paramètre de la règle doit être activé.",
'idsupdate flowbit file not found' => "Il n'y a pas d'avertissement flowbit pour le moment.",
'idsupdate name' => 'Nom',
'idsupdate state' => 'Etat',
'idsupdate type' => 'Type',
'idsupdate group' => 'Groupe',
'idsupdate test' => 'Tester',
'idsupdate set' => 'Définir/Non défini',
'idsupdate flowbit update time' => 'Avertissements Flowbit mis à jour à',
'idsupdate ids update' => 'Mise à jour IDS',
'idsupdate config' => 'Configuration',
'idsupdate enable automatic update' => 'Activer les mises à jour automatiques',
'idsupdate rate' => 'Taux de mise à jour',
'idsupdate download limit' => 'Limite de téléchargement (kbit/s)',
'idsupdate default policy' => 'Politique par défaut',
'idsupdate low memory usage' => 'Faible utilisation de la mémoire',
'idsupdate enable email' => 'Envoyer des emails',
'idsupdate apply policy change' => 'Appliquer les modifications de stratégie',
'idsupdate policy connectivity' => 'Connectivité',
'idsupdate policy balanced' => 'Équilibré',
'idsupdate policy security' => 'Sécurité',
'idsupdate policy max-detect' => 'Détection maximale',
'idsupdate hourly' => 'Horaire',
'idsupdate daily' => 'Journalier',
'idsupdate weekly' => 'Hebdomadaire',
'idsupdate status' => 'Statut',
'idsupdate ruleset' => 'Ensemble de règles',
'idsupdate last updated' => 'Dernière mise à jour',
'idsupdate invalid input for download limit' => 'Entrée non valide pour la limite de téléchargement',
'idsupdate force policy change' => 'Force la politique à la prochaine mise à jour'
);
