# Added for Automated IDS Update accounting
%tr = (
%tr,
'idsupdate update status' => 'Status der Regelaktualisierung',
'idsupdate update failed' => 'Regelaktualisierung fehlgeschlagen',
'idsupdate update partial' => 'Regelaktualisierung teilweise abgeschlossen',
'idsupdate update success' => 'Regelupdate erfolgreich',
'idsupdate ids update log' => 'IDS-Aktualisierungsprotokolle',
'idsupdate ids update log viewer' => 'IDS Protokollanzeige aktualisieren',
'idsupdate updates' => 'Anzahl der Regelupdates für',
'idsupdate active rules' => 'Anzahl der aktiven Regeln',
'idsupdate ruleset' => 'Regelsatz',
'idsupdate new rules' => 'Neue Regeln',
'idsupdate enabled' => 'Aktiviert',
'idsupdate disabled' => 'Behindert',
'idsupdate deleted rules' => 'Gelöschte Regeln',
'idsupdate updated rules' => 'Aktualisierte Regeln',
'idsupdate changed enabled' => 'Aktivierte Regeln, die sich geändert haben',
'idsupdate consider disabling' => 'Die folgenden aktivierten Regeln wurden geändert, die normalerweise in der aktuell ausgewählten Richtlinie ' .
                                'deaktiviert wären. Es lohnt sich zu überlegen, ob die Gründe, aus denen sie aktiviert wurden, immer noch ' .
                                'gültig sind.',
'idsupdate changed disabled' => 'Deaktivierte Regeln, die sich geändert haben',
'idsupdate consider enabling' => 'Die folgenden deaktivierten Regeln wurden geändert, die normalerweise in der aktuell ausgewählten Richtlinie ' .
                               'aktiviert wären. Es lohnt sich zu überlegen, ob die Gründe für ihre Deaktivierung noch gültig sind.',
'idsupdate enabled' => 'Regeln, die aktiviert wurden',
'idsupdate enabled due to policy change' => 'Die folgenden Regeln wurden aufgrund einer Änderung der Richtlinie aktiviert',
'idsupdate disabled' => 'Regeln, die deaktiviert wurden',
'idsupdate disabled due to policy changed' => 'Die folgenden Regeln wurden aufgrund einer Änderung der Richtlinie deaktiviert',
'idsupdate change' => 'Veränderung',
'idsupdate from' => 'Von',
'idsupdate to' => 'Zu',
'idsupdate none found' => 'Keine gefunden in aktiven Regeldateien',
'idsupdate unrecognised log messages' => 'Unbekannte Einträge',
'idsupdate flowbit warnings' => 'Es gibt Warnungen für Flussbits, die in den aktiven Regeln getestet werden, ohne dass sie gesetzt werden.',
'idsupdate flowbit warning list' => 'Intrusion Detection System Regel Flowbit Warnungen',
'idsupdate flowbit warning explaination' => 'Flowbits erlauben einer IDS-Regel, nachfolgende Regeln zu beeinflussen. Die folgende Liste enthält ' .
                                          'Regeln, die den Wert von Flussbits testen, wobei jedoch keine aktive Regel das Flussbit festlegt. ' .
                                          'Entweder die Regel, die das Flowbit testet, sollte deaktiviert sein oder die Regel, die das Flowbit ' .
                                          'setzt, sollte aktiviert sein.',
'idsupdate flowbit file not found' => 'Zu diesem Zeitpunkt gibt es keine Flowbit-Warnungen.',
'idsupdate name' => 'Nennen',
'idsupdate state' => 'Zustand',
'idsupdate type' => 'Typ',
'idsupdate group' => 'Gruppe',
'idsupdate test' => 'Prüfung',
'idsupdate set' => 'Festlegen / Aufheben',
'idsupdate flowbit update time' => 'Flowbit-Warnungen aktualisiert um',
'idsupdate ids update' => 'IDS-Aktualisierung',
'idsupdate config' => 'Konfiguration',
'idsupdate enable automatic update' => 'Aktivieren Sie automatische Updates',
'idsupdate rate' => 'Aktualisierungsrate',
'idsupdate download limit' => 'Downloadlimit (kbit/s)',
'idsupdate default policy' => 'Standardrichtlinie',
'idsupdate live update' => 'Live-Aktualisierung aktivieren',
'idsupdate enable email' => 'E-Mails senden',
'idsupdate apply policy change' => 'Wenden Sie Richtlinienänderungen an',
'idsupdate policy connectivity' => 'Konnektivität',
'idsupdate policy balanced' => 'Ausgewogen',
'idsupdate policy security' => 'Sicherheit',
'idsupdate policy max-detect' => 'Max-Erkennung',
'idsupdate hourly' => 'Stündlich',
'idsupdate daily' => 'Täglich',
'idsupdate weekly' => 'Wöchentlich',
'idsupdate status' => 'Status',
'idsupdate ruleset' => 'Ruleset',
'idsupdate last updated' => 'Regelsatz',
'idsupdate invalid input for download limit' => 'Ungültige Eingabe für Downloadlimit'
);
