# Added for Automated IDS Update accounting
%tr = (
%tr,
'idsupdate update status' => 'Estado de actualización de la regla',
'idsupdate update failed' => 'La actualización de la regla falló',
'idsupdate update partial' => 'Actualización de la regla parcialmente completada',
'idsupdate update success' => 'Actualización de la regla exitosa',
'idsupdate ids update log' => 'Registros de actualización IDS',
'idsupdate ids update log viewer' => 'Actualizar el visor de registro IDS',
'idsupdate updates' => 'Número de actualizaciones de reglas para',
'idsupdate active rules' => 'Número de reglas activas',
'idsupdate ruleset' => 'Conjunto de reglas',
'idsupdate new rules' => 'Nuevas reglas',
'idsupdate enabled' => 'Habilitado',
'idsupdate disabled' => 'Incapacitado',
'idsupdate deleted rules' => 'Reglas eliminadas',
'idsupdate updated rules' => 'Reglas actualizadas',
'idsupdate changed enabled' => 'Habilitado reglas que han cambiado',
'idsupdate consider disabling' => 'Las siguientes reglas habilitadas han cambiado y normalmente se inhabilitarían en la política actualmente ' .
                                'seleccionada. Vale la pena considerar si los motivos por los que fueron habilitados siguen siendo válidos.',
'idsupdate changed disabled' => 'Reglas desactivadas que han cambiado',
'idsupdate consider enabling' => 'Las siguientes reglas desactivadas han cambiado y normalmente se habilitarían en la política actualmente ' .
                               'seleccionada. Vale la pena considerar si las razones por las que fueron deshabilitadas siguen siendo válidas.',
'idsupdate enabled' => 'Nuevas reglas que han sido habilitadas',
'idsupdate enabled due to policy change' => 'Las siguientes reglas se han habilitado debido a un cambio en la política',
'idsupdate disabled' => 'Nuevas reglas que han sido deshabilitadas.',
'idsupdate disabled due to policy changed' => 'Las siguientes reglas se han desactivado debido a un cambio en la política',
'idsupdate change' => 'Cambio',
'idsupdate from' => 'De',
'idsupdate to' => 'A',
'idsupdate none found' => 'No se encontró ninguno en los archivos de reglas activas',
'idsupdate unrecognised log messages' => 'Entradas desconocidas',
'idsupdate flowbit warnings' => 'Hay advertencias para los bits de flujo que se prueban en las reglas activas sin establecerse.',
'idsupdate flowbit warning list' => 'Advertencias de flujo de la regla del sistema de detección de intrusos',
'idsupdate flowbit warning explaination' => 'Flowbits permite que una regla de IDS afecte las reglas subsiguientes. La siguiente lista es de reglas que '.
                                          'probar el valor de los bits de flujo, pero donde ninguna regla activa establece el flujo de bits. O la ' .
                                          'prueba de la regla el flujo de bits debe estar desactivado o la regla que establece el flujo de bits debe ' .
                                          'estar habilitada.',
'idsupdate flowbit file not found' => 'No hay advertencias de flujo de bits en este momento.',
'idsupdate name' => 'Nombre',
'idsupdate state' => 'Estado',
'idsupdate type' => 'Tipo',
'idsupdate group' => 'Grupo',
'idsupdate test' => 'Prueba',
'idsupdate set' => 'Establecer/Desestablecer',
'idsupdate flowbit update time' => 'Advertencias Flowbit actualizadas en',
'idsupdate ids update' => 'Actualización de IDS',
'idsupdate config' => 'Configuración',
'idsupdate enable automatic update' => 'Habilitar actualizaciones automáticas',
'idsupdate rate' => 'Frecuencia de actualización',
'idsupdate download limit' => 'Límite de descarga (kbit/s)',
'idsupdate default policy' => 'Política predeterminada',
'idsupdate low memory usage' => 'Bajo uso de memoria',
'idsupdate enable email' => 'Enviar correos electrónicos',
'idsupdate apply policy change' => 'Aplicar cambios de política',
'idsupdate policy connectivity' => 'Conectividad',
'idsupdate policy balanced' => 'Equilibrado',
'idsupdate policy security' => 'Seguridad',
'idsupdate policy max-detect' => 'Detección máxima',
'idsupdate hourly' => 'Cada hora',
'idsupdate daily' => 'Diario',
'idsupdate weekly' => 'Semanal',
'idsupdate status' => 'Estado',
'idsupdate ruleset' => 'Conjunto de reglas',
'idsupdate last updated' => 'Última actualización',
'idsupdate invalid input for download limit' => 'Entrada inválida para el límite de descarga',
'idsupdate force policy change' => 'Política de fuerza en la próxima actualización.'
);
